name: My-CI-Exercice

on:
  push:
    branches: [ my-exercices ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
      # Exo 1
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install, test, build
        run: |
          npm install
          npm test
          npm run build

      # Exo 2 & 3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        env:
          DOCKER_REGISTRY: 'docker.io'
          DOCKER_NAMESPACE: 'xebxke'
          DOCKER_IMAGE: 'camel'
          BRANCH: ${{ github.ref }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: docker.io/$DOCKER_NAMESPACE/$DOCKER_IMAGE:${BRANCH#refs/heads/}-COMMIT_SHA

      # Exo 2 - WIP failed
#      - name: Build Dockerfile
#        env:
#          DOCKER_REGISTRY: 'docker.io'
#          DOCKER_NAMESPACE: 'xebxke'
#          DOCKER_IMAGE: 'camel'
#          BRANCH: ${{ github.ref }}
#        run: |
#          echo ${DOCKER_NAMESPACE}
#          echo ${DOCKER_IMAGE}
#          echo ${GITHUB_SHA}
#          echo ${BRANCH}
#          docker build -t $DOCKER_REGISTRY/$DOCKER_NAMESPACE/$DOCKER_IMAGE:${BRANCH#refs/heads/}-$GITHUB_SHA ../../.

#          docker build -t docker.io/$DOCKER_NAMESPACE/$DOCKER_IMAGE:${BRANCH#refs/heads/}-COMMIT_SHA -f Dockerfile .
#          COMMIT_SHA: $GITHUB_SHA
