name: My-CI-Exercice

on:
  push:
    branches: [ my-exercices ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    env:
      BRANCH: ${{ github.head_ref }}
#      BRANCH: ${{ BRANCH#/ref/head/ }}
#      COMMIT: ${{ GITHUB_SHA::8 }}

    steps:
      # Exo 1
#      - uses: actions/checkout@v2
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v1
#        with:
#          node-version: ${{ matrix.node-version }}
#      - run: npm install
#      - run: npm test
#      - run: npm run build

      # Exo 2
      - name: Build Dockerfile
        run: |
          echo ${BRANCH_NAME}
          echo ${GITHUB_SHA}
#          docker build -t xbexke/camel:$BRANCH-$COMMIT -f Dockerfile .
