name: My-CI-Exercice

on:
  push:
    branches: [ my-exercices ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

    - name: Environnement
      uses: docker://node:8-alpine

    - name: Install, Test, Build
      run: |
        npm install
        npm test
        npm run build
